name: Update DESCRIPTION Authors

on:
  pull_request:
    branches: [dev]

jobs:
  check-authors:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    uses: FlorianSchw/package-workflows/.github/workflows/authors-suggest.yml@main
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
