name: Check DESCRIPTION Authors

on:
  pull_request:
    branches: [dev]
    paths: ['R/**']

jobs:
  check-authors:
    permissions:
      contents: write
      pull-requests: write
    uses: FlorianSchw/package-workflows/.github/workflows/check-description-authors.yml@main
