# .github/workflows/check.yml in the package repo
name: R CMD Check

on:
  pull_request:
    branches: [dev]
    paths: ['R/**', 'tests/**', '.github/**', 'DESCRIPTION', 'NAMESPACE']
  schedule:
    - cron: '15 7 * * 1'
  workflow_dispatch:

jobs:
  check:
    uses: FlorianSchw/package-workflows/.github/workflows/R-CMD-Check.yml@main
    with:
      extra-apt-packages: ''
      extra-r-packages: ''
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
