name: Require Head Branch

on:
  pull_request:
    branches: [main]

jobs:
  require-head-branch:
    uses: FlorianSchw/package-workflows/.github/workflows/require-head-branch.yml@main
    with:
      allowed-head: 'dev'
